### ISSUE TITLE
CPU autoscaling not working

### ISSUE THREAD

**Issue by brianread108** [fabriziosalmi/proxmox-vm-autoscale#12]
Getting this:

2024-11-12 06:48:21,640 [WARNING] vm_resource_manager: All parsing methods failed for output: blockstat:
ide2:
		account_failed: 1
		account_invalid: 1
		failed_flush_operations: 0
		failed_rd_operations: 0
		failed_unmap_operations: 0
		failed_wr_operations: 0
		failed_zone_append_operations: 0
		flush_operations: 0
		flush_total_time_ns: 0
		idle_time_ns: 10760148069454
		invalid_flush_operations: 0
		invalid_rd_operations: 0
		invalid_unmap_operations: 0
		invalid_wr_operations: 0
		invalid_zone_append_operations: 0
		rd_bytes: 152
		rd_merged: 0
		rd_operations: 4
		rd_total_time_ns: 171432
		timed_stats:
		unmap_bytes: 0
		unmap_merged: 0
		unmap_operations: 0
		unmap_total_time_ns: 0
		wr_bytes: 0
		wr_highest_offset: 0
		wr_merged: 0
		wr_operations: 0
		wr_total_time_ns: 0
		zone_append_bytes: 0
		zone_append_merged: 0
		zone_append_operations: 0
		zone_append_total_time_ns: 0
	scsi0:
		account_failed: 1
		account_invalid: 1
		failed_flush_operations: 0
		failed_rd_operations: 0
		failed_unmap_operations: 0
		failed_wr_operations: 0
		failed_zone_append_operations: 0
		flush_operations: 6925
		flush_total_time_ns: 1797252065
		idle_time_ns: 1729210175
		invalid_flush_operations: 0
		invalid_rd_operations: 0
		invalid_unmap_operations: 0
		invalid_wr_operations: 0
		invalid_zone_append_operations: 0
		rd_bytes: 1573970944
		rd_merged: 0
		rd_operations: 53353
		rd_total_time_ns: 1461573692046
		timed_stats:
		unmap_bytes: 0
		unmap_merged: 0
		unmap_operations: 0
		unmap_total_time_ns: 0
		wr_bytes: 357163008
		wr_highest_offset: 399433564160
		wr_merged: 0
		wr_operations: 33587
		wr_total_time_ns: 1179364176892
		zone_append_bytes: 0
		zone_append_merged: 0
		zone_append_operations: 0
		zone_append_total_time_ns: 0
cpus: 1
disk: 0
diskread: 1573971096
diskwrite: 357163008
maxdisk: 536870912000
maxmem: 6442450944
mem: 4202268340
name: Mailserver
netin: 1353209358
netout: 1345873382
nics:
	tap101i0:
		netin: 157846225
		netout: 1196026259
	tap101i1:
		netin: 1195363133
		netout: 149847123
pid: 3621134
proxmox-support:
	backup-fleecing: 1
	backup-max-workers: 1
	pbs-dirty-bitmap: 1
	pbs-dirty-bitmap-migration: 1
	pbs-dirty-bitmap-savevm: 1
	pbs-library-version: 1.4.1 (UNKNOWN)
	pbs-masterkey: 1
	query-bitmap-info: 1

**Comment by fabriziosalmi** [comment]
I will try to focus on this in the next free time slot, thank you to point me out to that.

**Comment by fabriziosalmi** [comment]
I will try this approach, if you want to test it out and feedback if have time it will be really appreciated :)

```
import logging
import re
import time
from dataclasses import dataclass
from typing import Tuple, Optional, Dict, Any
from enum import Enum, auto


class ScaleDirection(Enum):
    """Enum for scaling directions to avoid string literals."""
    UP = auto()
    DOWN = auto()


@dataclass
class ResourceLimits:
    """Data class to store resource limits configuration."""
    min_cores: int = 1
    max_cores: int = 8
    min_ram: int = 512  # MB
    max_ram: int = 16384  # MB
    ram_step: int = 512  # MB
    scale_cooldown: int = 300  # seconds


class VMResourceError(Exception):
    """Custom exception for VM resource-related errors."""
    pass


class VMResourceManager:
    """Manages VM resources including CPU and RAM scaling."""
    
    def __init__(self, ssh_client: Any, vm_id: int, config: Dict[str, Any]):
        """
        Initialize the VM Resource Manager.
        
        Args:
            ssh_client: SSH client instance for executing commands
            vm_id: ID of the VM to manage
            config: Configuration dictionary
        """
        self.ssh_client = ssh_client
        self.vm_id = vm_id
        self.limits = ResourceLimits(
            min_cores=config.get('min_cores', ResourceLimits.min_cores),
            max_cores=config.get('max_cores', ResourceLimits.max_cores),
            min_ram=config.get('min_ram', ResourceLimits.min_ram),
            max_ram=config.get('max_ram', ResourceLimits.max_ram),
            ram_step=config.get('ram_step', ResourceLimits.ram_step),
            scale_cooldown=config.get('scale_cooldown', ResourceLimits.scale_cooldown)
        )
        self.logger = logging.getLogger("vm_resource_manager")
        self.last_scale_time = 0

    def execute_command(self, command: str, retries: int = 3) -> str:
        """
        Execute command with retry logic and proper error handling.
        
        Args:
            command: Command to execute
            retries: Number of retry attempts
            
        Returns:
            Command output as string
            
        Raises:
            VMResourceError: If command execution fails after retries
        """
        for attempt in range(retries):
            try:
                self.logger.debug(f"Executing command: {command}")
                output = self.ssh_client.execute_command(command)
                return output.strip()
            except Exception as e:
                self.logger.warning(f"Attempt {attempt + 1}/{retries} failed: {str(e)}")
                if attempt == retries - 1:
                    raise VMResourceError(f"Command execution failed after {retries} attempts: {str(e)}")
                time.sleep(2 ** attempt)  # Exponential backoff
        
        raise VMResourceError(f"Unexpected error executing command after {retries} attempts")

    def is_vm_running(self, retries: int = 3, delay: int = 5) -> bool:
        """
        Check if the VM is running with improved error handling.
        
        Args:
            retries: Number of retry attempts
            delay: Delay between retries in seconds
            
        Returns:
            Boolean indicating if VM is running
        """
        try:
            output = self.execute_command(f"qm status {self.vm_id} --verbose", retries)
            status_match = re.search(r"status:\s*(\w+)", output.lower())
            
            if not status_match:
                raise VMResourceError("Could not parse VM status from output")
                
            status = status_match.group(1)
            is_running = status == "running"
            
            self.logger.info(f"VM {self.vm_id} status: {status}")
            return is_running
            
        except Exception as e:
            self.logger.error(f"Failed to check VM status: {str(e)}")
            return False

    def get_resource_usage(self) -> Tuple[float, float]:
        """
        Get current CPU and RAM usage percentages.
        
        Returns:
            Tuple of (CPU usage %, RAM usage %)
        """
        if not self.is_vm_running():
            return 0.0, 0.0

        try:
            output = self.execute_command(f"qm status {self.vm_id} --verbose")
            return self._parse_resource_usage(output)
        except Exception as e:
            self.logger.error(f"Failed to get resource usage: {str(e)}")
            return 0.0, 0.0

    def _parse_resource_usage(self, output: str) -> Tuple[float, float]:
        """
        Parse CPU and RAM usage from command output.
        
        Args:
            output: Command output string
            
        Returns:
            Tuple of (CPU usage %, RAM usage %)
        """
        cpu_usage = self._parse_cpu_usage(output)
        ram_usage = self._parse_ram_usage(output)
        
        self.logger.debug(f"Parsed resource usage - CPU: {cpu_usage}%, RAM: {ram_usage}%")
        return cpu_usage, ram_usage

    def _parse_cpu_usage(self, output: str) -> float:
        """Parse CPU usage with improved pattern matching."""
        try:
            # Support multiple CPU usage output formats
            patterns = [
                r"cpu(?:.*):\s*(\d+\.?\d*)%",
                r"cpu_usage:\s*(\d+\.?\d*)",
                r"cpu_percent:\s*(\d+\.?\d*)"
            ]
            
            for pattern in patterns:
                if match := re.search(pattern, output):
                    return float(match.group(1))
                    
            self.logger.warning("CPU usage not found in output")
            return 0.0
            
        except Exception as e:
            self.logger.error(f"Error parsing CPU usage: {str(e)}")
            return 0.0

    def _parse_ram_usage(self, output: str) -> float:
        """Parse RAM usage with improved error handling."""
        try:
            max_mem_match = re.search(r"maxmem\s*:\s*(\d+)", output)
            mem_match = re.search(r"mem\s*:\s*(\d+)", output)

            if not (max_mem_match and mem_match):
                self.logger.warning("RAM usage information not found in output")
                return 0.0

            max_mem = int(max_mem_match.group(1))
            mem = int(mem_match.group(1))

            if max_mem <= 0:
                self.logger.warning("Invalid maximum memory value")
                return 0.0

            return (mem / max_mem) * 100

        except Exception as e:
            self.logger.error(f"Error parsing RAM usage: {str(e)}")
            return 0.0

    def scale_resources(self, cpu_usage: float, ram_usage: float, threshold_high: float = 80.0, threshold_low: float = 20.0) -> None:
        """
        Scale resources based on usage thresholds.
        
        Args:
            cpu_usage: Current CPU usage percentage
            ram_usage: Current RAM usage percentage
            threshold_high: High usage threshold percentage
            threshold_low: Low usage threshold percentage
        """
        if not self.can_scale():
            return

        try:
            # Scale CPU
            if cpu_usage > threshold_high:
                self.scale_cpu(ScaleDirection.UP)
            elif cpu_usage < threshold_low:
                self.scale_cpu(ScaleDirection.DOWN)

            # Scale RAM
            if ram_usage > threshold_high:
                self.scale_ram(ScaleDirection.UP)
            elif ram_usage < threshold_low:
                self.scale_ram(ScaleDirection.DOWN)

        except Exception as e:
            self.logger.error(f"Failed to scale resources: {str(e)}")
            raise VMResourceError(f"Resource scaling failed: {str(e)}")

    def can_scale(self) -> bool:
        """Check if scaling is allowed based on cooldown period."""
        current_time = time.time()
        elapsed_time = current_time - self.last_scale_time
        
        if elapsed_time < self.limits.scale_cooldown:
            remaining_time = int(self.limits.scale_cooldown - elapsed_time)
            self.logger.info(f"Scaling on cooldown. {remaining_time} seconds remaining.")
            return False
            
        return True

    def scale_cpu(self, direction: ScaleDirection) -> None:
        """
        Scale CPU cores and vCPUs.
        
        Args:
            direction: ScaleDirection.UP or ScaleDirection.DOWN
        """
        if not self.can_scale():
            return

        try:
            current_cores = self._get_current_cores()
            current_vcpus = self._get_current_vcpus()

            if direction == ScaleDirection.UP and current_cores < self.limits.max_cores:
                self._scale_cpu_up(current_cores, current_vcpus)
            elif direction == ScaleDirection.DOWN and current_cores > self.limits.min_cores:
                self._scale_cpu_down(current_cores, current_vcpus)
            else:
                self.logger.info("No CPU scaling required")

            self.last_scale_time = time.time()

        except Exception as e:
            raise VMResourceError(f"CPU scaling failed: {str(e)}")

    def scale_ram(self, direction: ScaleDirection) -> None:
        """
        Scale RAM allocation.
        
        Args:
            direction: ScaleDirection.UP or ScaleDirection.DOWN
        """
        if not self.can_scale():
            return

        try:
            current_ram = self._get_current_ram()

            if direction == ScaleDirection.UP and current_ram < self.limits.max_ram:
                new_ram = min(current_ram + self.limits.ram_step, self.limits.max_ram)
                self._set_ram(new_ram)
            elif direction == ScaleDirection.DOWN and current_ram > self.limits.min_ram:
                new_ram = max(current_ram - self.limits.ram_step, self.limits.min_ram)
                self._set_ram(new_ram)
            else:
                self.logger.info("No RAM scaling required")

            self.last_scale_time = time.time()

        except Exception as e:
            raise VMResourceError(f"RAM scaling failed: {str(e)}")

    def _get_current_vcpus(self) -> int:
        """Get current vCPU count."""
        try:
            output = self.execute_command(f"qm config {self.vm_id}")
            if match := re.search(r"vcpus:\s*(\d+)", output):
                return int(match.group(1))
            return 1
        except Exception as e:
            self.logger.error(f"Failed to get vCPUs: {str(e)}")
            return 1

    def _get_current_cores(self) -> int:
        """Get current CPU cores count."""
        try:
            output = self.execute_command(f"qm config {self.vm_id}")
            if match := re.search(r"cores:\s*(\d+)", output):
                return int(match.group(1))
            return 1
        except Exception as e:
            self.logger.error(f"Failed to get CPU cores: {str(e)}")
            return 1

    def _get_current_ram(self) -> int:
        """Get current RAM allocation in MB."""
        try:
            output = self.execute_command(f"qm config {self.vm_id}")
            if match := re.search(r"memory:\s*(\d+)", output):
                return int(match.group(1))
            return self.limits.min_ram
        except Exception as e:
            self.logger.error(f"Failed to get current RAM: {str(e)}")
            return self.limits.min_ram

    def _set_ram(self, ram: int) -> None:
        """Set RAM allocation."""
        try:
            self.execute_command(f"qm set {self.vm_id} -memory {ram}")
            self.logger.info(f"RAM set to {ram} MB for VM {self.vm_id}")
        except Exception as e:
            raise VMResourceError(f"Failed to set RAM to {ram}MB: {str(e)}")

    def _scale_cpu_up(self, current_cores: int, current_vcpus: int) -> None:
        """Scale up CPU cores and vCPUs."""
        new_cores = current_cores + 1
        self._set_cores(new_cores)
        new_vcpus = min(current_vcpus + 1, new_cores)
        self._set_vcpus(new_vcpus)

    def _scale_cpu_down(self, current_cores: int, current_vcpus: int) -> None:
        """Scale down CPU cores and vCPUs."""
        new_vcpus = max(current_vcpus - 1, 1)
        self._set_vcpus(new_vcpus)
        new_cores = current_cores - 1
        self._set_cores(new_cores)

    def _set_cores(self, cores: int) -> None:
        """Set CPU cores count."""
        try:
            self.execute_command(f"qm set {self.vm_id} -cores {cores}")
            self.logger.info(f"CPU cores set to {cores} for VM {self.vm_id}")
        except Exception as e:
            raise VMResourceError(f"Failed to set CPU cores to {cores}: {str(e)}")

    def _set_vcpus(self, vcpus: int) -> None:
        """Set vCPU count."""
        try:
            self.execute_command(f"qm set {self.vm_id} -vcpus {vcpus}")
            self.logger.info(f"vCPUs set to {vcpus} for VM {self.vm_id}")
        except Exception as e:
            raise VMResourceError(f"Failed to set vCPUs to {vcpus}: {str(e)}")
```

**Comment by fabriziosalmi** [comment]
Should be fixed with [this commit](https://github.com/fabriziosalmi/proxmox-vm-autoscale/commit/a445a129103a7ac80f27f9a74e60f17fac5b5ad9), let me know if u can 🍻

**Comment by brianread108** [comment]
ok, now it gives:

Dec 03 19:01:43 pve python3[815037]: WARNING: No notification method is enabled. Message: Error processing VM 101 on host pve: the JSON object must be str, bytes or bytearray, not tuple

**Comment by brianread108** [comment]
The email notification in the config.yaml look like this: 
alerts:
  email_enabled: true
  email_recipient: smeserver@bjsystems.co.uk
  smtp_server: mail.bjsystems.co.uk
  smtp_port: 465
  smtp_user: smeserver
  smtp_password: xxxxxxxx

**Comment by fabriziosalmi** [comment]
Notification sent as warning not as an error. Of course can be improved.
For the tuple stuff I'll go investigate very soon, ty to point me out to that, not 1st time facing such kind of issues in this project :)

**Comment by fabriziosalmi** [comment]
tuple issue should be fixed [here](https://github.com/fabriziosalmi/proxmox-vm-autoscale/commit/346918980138b1c4b6288bccdee42a7d2895217c), working on notification fix.

**Comment by fabriziosalmi** [comment]
Notification issue should be addressed [here](https://github.com/fabriziosalmi/proxmox-vm-autoscale/commit/5e50464438bed6c63f39e6945a4f9e1dcfb3e958).

Thank you for your help in improving and fixing the project.

**Comment by Nicarex** [comment]
I just downloaded the latest version, but I’m still getting the same error as above:

Dec 07 01:25:35 pve python3[50683]: INFO: Connected (version 2.0, client OpenSSH_9.2p1)
Dec 07 01:25:35 pve python3[50683]: INFO: Authentication (publickey) successful!
Dec 07 01:25:35 pve python3[50683]: INFO: Successfully connected to 192.168.10.104 on port 22
Dec 07 01:25:36 pve python3[50683]: INFO: Command executed successfully on 192.168.10.104: qm status 108 --verbose
Dec 07 01:25:36 pve python3[50683]: INFO: VM 108 is running.
Dec 07 01:25:37 pve python3[50683]: INFO: Command executed successfully on 192.168.10.104: pvesh get /nodes/$(hostname)/status --output-format json
Dec 07 01:25:37 pve python3[50683]: ERROR: Failed to check host resources: the JSON object must be str, bytes or bytearray, not tuple
Dec 07 01:25:37 pve python3[50683]: ERROR: Error processing VM 108 on host pve: the JSON object must be str, bytes or bytearray, not tuple
Dec 07 01:25:37 pve python3[50683]: WARNING: Failed to send notification through any channel. Message: Error processing VM 108 on host pve: the JSON object must be str, bytes or bytearray, not tuple
Dec 07 01:25:37 pve python3[50683]: INFO: SSH connection closed for 192.168.10.104

**Comment by fabriziosalmi** [comment]
Host resource checker updated using [this approach](https://github.com/fabriziosalmi/proxmox-vm-autoscale/commit/27c2b22a17e37e178d5a9a1f7f143129657eb714)

**Comment by fabriziosalmi** [comment]
Notification issue updated autoscale.py using [this approach](https://github.com/fabriziosalmi/proxmox-vm-autoscale/commit/0489ceeb7f95a0bdfe5573b094cdd200b1bc3105).

**Comment by brianread108** [comment]
Errors above fixed by:

https://github.com/fabriziosalmi/proxmox-vm-autoscale/pull/17
and:
https://github.com/fabriziosalmi/proxmox-vm-autoscale/pull/16

Individual CPU usage still not found, closing this and will open a new issue.
